### ISSUE TITLE
read file hdf5

### ISSUE THREAD

**Issue by DomenicoGaudioso** [LiorBanai/HDF5-CSharp#113]
Hi, sorry for the inconvenience but I have a question.
i am a python user and i have red hdf5 files with h5py. I am now working within .net environment and I am looking to use your library with IronPython.
I would like to understand how can I get a specific data within the database and how to get access to the different trees.
Any help are super appreciated.

I leave you an example of how I access the file in python ('readH5.py').
I am also attaching the hdf5 file that I would like to use ('recorder.hdf5')

Regards

Domenico

[file.zip](https://github.com/LiorBanai/HDF5-CSharp/files/6054932/file.zip)

**Comment by LiorBanai** [comment]
Hi @DomenicoGaudioso ,
Basically you create a .net class that represent your dataset.
few questions:
1. Are you looking to read the entire file or only specific datasets? if specific dataset please write which one so I will check the dataset.
2. is the file structure always the same or is it dynamically create at runtime?
3. Do you need to modify it  or just read back in .net?

**Comment by DomenicoGaudioso** [comment]
thanks for the immediate response, I answer your questions.
1. I am trying to read a specific set of data.
in particular, with python it is as if it were a dictionary so what I do is this: 

f = h5py.File(r'C:\recorder.hdf5','r') 
dset = f['MODEL_STAGE[1]']['MODEL']['NODES']['COORDINATES'][1]
*in the square brackets you see the opening keys I used to find my dataset
2. the file structure is more or less always the same
3. i just need to read it in .net

**Comment by LiorBanai** [comment]
Then it is very easy:
You first can set some error handling:
```cs 
...
Hdf5.Settings.LowerCaseNaming = false;
Hdf5.Settings.EnableErrorReporting(true);
Hdf5Utils.LogWarning = (s) => Errors.Add(s);
Hdf5Utils.LogError = (s) => Errors.Add(s);
```

then you create a class that represent your data:

```cs
public class Coordinate
{
       [Hdf5EntryName("COORDINATES")] public double[,] COORDINATES { get; set; }
}
```
and the you just read it:

```cs

string filename = @"recorder.hdf5"; \\full path
long fileId = -1;
try
{
        fileId = Hdf5.OpenFile(filename, true);
        var result = Hdf5.ReadObject<Coordinate>(fileId, "/MODEL_STAGE[1]/MODEL/NODES");
}
 finally
 {
        if (fileId > 0)
           {
             Hdf5.CloseFile(fileId);
            }
 }
```

the result is matrix of 1817,3 (in tihs case):
![image](https://user-images.githubusercontent.com/36262995/109394981-9cbeae80-7932-11eb-96f2-6f1b6aa9c618.png)

**Comment by Marco-Pellegrino** [comment]
Thanks @LiorBanai!
it looks like that it is possible to read the data! Amazing

Do you have any experience with IronPython?
Me and @DomenicoGaudioso need to translate what you have written in C# for IronPython and It would be amazing if you already know the answer.

**Comment by LiorBanai** [comment]
not sure why you need IronPython with this. IronPython is an implementation of the Python programming language targeting the .NET Framework and Mono. This means you are already running under .net so you can use the code I wrote above.
If you want to run python inside .net (Iron Python) then it is no clear to me why you cannot use python  h5 code to read it. You basically run python inside .net if I'm not mistaken..

**Comment by Marco-Pellegrino** [comment]
We are writing a plug-in for a software where it is possible to write with C# or IronPython 2.7 and me and Domenico are familiar with python.
I was thinking that h5py was using numpy under the hood but I could be wrong and numpy is not available for ironPython 2.7 and this is the reason for use your library.

**Comment by Marco-Pellegrino** [comment]
Hi @LiorBanai 
I have manage to translate your code in C# and it works!
Thanks.
How would you read the DISPLACEMENT for different time step with your approach?
Step_0
Step_1

![image](https://user-images.githubusercontent.com/53620289/109848692-72c5fe80-7c48-11eb-84c4-1e766fbd423a.png)


Thanks,
Marco

**Comment by LiorBanai** [comment]
Hi @Marco-Pellegrino ,
Glad to hear you managed to use the library.
for the different steps dataset I would use something like this:
```cs
        public class Steps
        {
            [Hdf5EntryName("STEP_0")] public double[,] STEP0 { get; set; }
            [Hdf5EntryName("STEP_1")] public double[,] STEP1 { get; set; }

        }
```
and read it:

```cs
                fileId = Hdf5.OpenFile(filename, true);
                Assert.IsTrue(fileId > 0);
                var step = "/MODEL_STAGE[1]/RESULTS/ON_NODES/DISPLACEMENT/DATA";
                var result2 = Hdf5.ReadObject<Steps>(fileId, step);
```

In the future I'll add option to read it dynamically without needing to specify each name (step_0, step_1) so you could  read wit hsingle step_+number

**Comment by DomenicoGaudioso** [comment]
Hi @LiorBanai , I'm sorry but I'll ask you another little question.
How would you read this data? I'm having trouble getting into '53 -UnknownMovableObject [201: 0] '.
Thanks for the help.

Best

![image](https://user-images.githubusercontent.com/43296235/110255403-ccedf900-7f93-11eb-9bef-5632ce0d711f.png)

**Comment by LiorBanai** [comment]
I'll add in the coming weekend a generic Mathis to read and 2d matrix so you will be able to use same object for all your matrices. It will simplify your usage.

**Comment by DomenicoGaudioso** [comment]
thanks, you are the best.

**Comment by DomenicoGaudioso** [comment]
Hi Liron, did you add something that suits us? thanks for the help

**Comment by LiorBanai** [comment]
no yet, bein busy.
will do it tomorrow or the day after

**Comment by LiorBanai** [comment]
Ok, so I created new method to read tabular data.
the way to use it is follow:
1. open the file using ``` fileId = Hdf5.OpenFile(filename, true);```
2. Specify the path to the groupname and open it: ```  var groupId = Hdf5.CreateOrOpenGroup(fileId, groupName );```
3. Read the data in T[,] using the name of the dataset: ``` var tableOfData = Hdf5.Read2DTable<double>(groupId, "STEP_0"); ```

```csharp
                fileId = Hdf5.OpenFile(filename, true);
                var groupName = "/MODEL_STAGE[1]/RESULTS/ON_NODES/DISPLACEMENT/DATA";
                var groupId = Hdf5.CreateOrOpenGroup(fileId, groupName );
                var tableOfData = Hdf5.Read2DTable<double>(groupId, "STEP_0");
```

so in your case just call the ```Read2DTable``` methods with "STEP_0","STEP_1", etc .

update your nuget package to V1.12.2:
https://www.nuget.org/packages/HDF5-CSharp/1.12.2

**Comment by LiorBanai** [comment]
The data will be in public property inside the tableOfData class (you can ignore the other null property inside):
![image](https://user-images.githubusercontent.com/36262995/111868654-e3c52000-8983-11eb-8732-7d0b477f4554.png)

**Comment by DomenicoGaudioso** [comment]
Thank you so much,  I'll try it these days.

**Comment by LiorBanai** [comment]
I knew I remember the step_X data :)
this the same as https://github.com/LiorBanai/HDF5-CSharp/issues/201 so closing this one :)
