### ISSUE TITLE
Cannot Edit Attributes?

### ISSUE THREAD

**Issue by ChasenRanger** [LiorBanai/HDF5-CSharp#114]
Calling WriteAttribute() works perfectly well when creating a new one in a file, but attempting to change them later with WriteAttribute() leads to the following error:
![image](https://user-images.githubusercontent.com/48223850/109533716-888cc580-7a88-11eb-9944-90d70afbf3bd.png)

I figured I would try to delete them first, but I can't figure out how to do that, either. Although, since HDF5 doesn't repack automatically that's probably fine to avoid worrying about.

Curiously, I think attributes used to overwrite, but its possible I didn't notice the error before, too.

Some extra notes: The attributes in question are primitive types and not arrays.

**Comment by LiorBanai** [comment]
I think the entire library needs Refactor in regard to updating existing files. I think the standard use cases are fir creating /reading files and not modify them.. Usually user are creating h5 files in Python it seems and the try to read in c# and vice versa..

I do think a support for editing will add value. Maybe add file use mode (create/edit /read) in the hdf5 settings class

**Comment by ChasenRanger** [comment]
To add some extra notes: I have not noticed errors such as the above happening when overwriting datasets, and can confirm they are overwritten correctly as well. 

Adding a create/edit/read mode would be useful and consistent with other file streams, including Python as you mentioned. In that vein, converting to a more .net IOStream-like object could be useful, but I think it would be a lot more work than is necessary.

**Comment by LiorBanai** [comment]
For datasets I actually wrote specific code to enable overriding existing data 🙂.

I think I should do the same for all types with the create/read only /edit modes as flags..

**Comment by LiorBanai** [comment]
it was also easy to add support for overriding attributes in the current design so I have added it . Still I plan to do the new design in the near future. :)
