### ISSUE TITLE
System.NullReferenceException in Hdf5.ReadStringAttributes

### ISSUE THREAD

**Issue by svenrog** [LiorBanai/HDF5-CSharp#125]
When trying to load model weights exported from Python Tensorflow 2.5.0 (ISR RDN) a `System.NullReferenceException` is thrown while reading `'layer_names'` at `Hdf5Attributes.cs:134`. It looks like the pointer fails to resolve inside `Marshal.ReadByte`.

The local variable `count` is 124 although the length of the list presented inside HDFView is 414.
![image](https://user-images.githubusercontent.com/397214/112718590-5d18c180-8ef4-11eb-8699-a3d98dec46d5.png)

Please find the model attached for debugging purposes.
https://drive.google.com/file/d/1VOmjS0hfCJBtOB13rfunxw7oR7ItW224/view

**Comment by LiorBanai** [comment]
Hi, I cannot access the file. getting:
"You need access
Ask for access, or switch to an account with access. Learn more"

**Comment by svenrog** [comment]
I've adjusted access to the file. Hope it works better now.

**Comment by LiorBanai** [comment]
yes, I managed to download it. Will check and update you

**Comment by LiorBanai** [comment]
Hi @svenrog, I have managed to read the attributes:
![image](https://user-images.githubusercontent.com/36262995/112766552-fb9f4280-901a-11eb-9992-d859a88d4d80.png)

please make sure to use the latest version and specify the following attributes:
![image](https://user-images.githubusercontent.com/36262995/112766586-28535a00-901b-11eb-868d-ec692576f7cb.png)


```csharp
        public void ReadStringAttributes()
        {
            string filename = @"E:\artifact-cancel.hdf5";
            var openFileId = Hdf5.OpenFile(filename);
            Hdf5.Settings.CharacterPaddingType = CharacterPaddingType.NULLTERM;
            Hdf5.Settings.CharacterSetType = CharacterSetType.ASCII;
            var data = Hdf5.ReadStringAttributes(openFileId, "layer_names","");
           Hdf5.CloseFile(openFileId);
        }
```

**Comment by svenrog** [comment]
Thanks for the help. I'll bump this over to the Tensorflow.Net repo where that code resides.

**Comment by LiorBanai** [comment]
> Thanks for the help. I'll bump this over to the Tensorflow.Net repo where that code resides.

What do you mean by "I'll bump this over to the Tensorflow.Net repo where that code resides."?

**Comment by svenrog** [comment]
I was just talking about the dependencies of the packages I'm using in my project.
![image](https://user-images.githubusercontent.com/397214/112770754-77ec5280-9028-11eb-999e-991c443354f8.png)

The SciSharp-guys are using a forked version of your code, so I figured I'd post my question here.
https://github.com/SciSharp/HDF5-CSharp

**Comment by LiorBanai** [comment]
Ah I see 🙂
