### ISSUE TITLE
1 how to write attribute for a dataset; 2 how to list attributes of a group

### ISSUE THREAD

**Issue by Fokatu** [LiorBanai/HDF5-CSharp#163]
1 how to write attribute for a dataset; 2 how to list attributes of a group

Thanks!

**Comment by LiorBanai** [comment]
Hi,
You cna use the following example:
```cs
        [TestMethod]
        public void WriteAndReadAttribute()
        {
            string filename = Path.Combine(folder, "testAttribute.H5");
            try
            {
                var fileId = Hdf5.CreateFile(filename);
                Assert.IsTrue(fileId > 0);
                var groupId = Hdf5.CreateOrOpenGroup(fileId, "test");
                DateTime nowTime = DateTime.Now;
                Hdf5.WriteAttribute(groupId, "time", nowTime);
                Hdf5.WriteAttributes<DateTime>(groupId, "times", new List<DateTime> { nowTime, nowTime.AddDays(1) }.ToArray());

                DateTime readTime = Hdf5.ReadAttribute<DateTime>(groupId, "time");
                var allTimes = Hdf5.ReadAttributes<DateTime>(groupId, "times");

                Assert.IsTrue(readTime == nowTime);
                Assert.IsTrue(Hdf5.CloseFile(fileId) == 0);
            }
            catch (Exception ex)
            {
                CreateExceptionAssert(ex);
            }
        }
```

where the relevant part are :
```cs
                Hdf5.WriteAttribute(groupId, "time", nowTime);
                Hdf5.WriteAttributes<DateTime>(groupId, "times", new List<DateTime> { nowTime, nowTime.AddDays(1) }.ToArray());
```

![image](https://user-images.githubusercontent.com/36262995/142417685-d6077693-d969-4249-8fdd-059138a4c726.png)

**Comment by marksimer** [comment]
@LiorBanai  ,I have the same qustion, how to list attributes of a group/file/dataset? 
I noticed the **Hdf5.ReadAttribute** function, but I don't know how to use it?

**Comment by LiorBanai** [comment]
Hi @marksimer ,
you jsut need to pass the id of group/file/dataset of the element that has the attribute and the attribute name (like the example above)

**Comment by Fokatu** [comment]
the function "Hdf5.ReadAttributes<DateTime>(groupId, "times");" needs "<DateTime>", what if we donot know this param, i.e., how to read a hdf5 createa by others

**Comment by LiorBanai** [comment]
do you have the hdf5view?
use it to see the element name (like test in the screenshot above)
the open the file:
```cs
                var fileId = Hdf5.OpenFile(filename);
```
open the group:
 ```cs
               var groupId = Hdf5.CreateOrOpenGroup(fileId, "test");
````
and read the data:
```cs
                DateTime readTime = Hdf5.ReadAttribute<DateTime>(groupId, "time");
                var allTimes = Hdf5.ReadAttributes<DateTime>(groupId, "times");
```
the type depends on your data type.

**Comment by LiorBanai** [comment]
if this does not work please share your file

**Comment by Fokatu** [comment]
Yes, I do have hdfview. But is it possible for HDF5-CSharp to return the datatype? What I want is the function that the hdfview provides, i.e., parse the hdf5 file and list all the attributes.

**Comment by marksimer** [comment]
[hdf5_test.zip](https://github.com/LiorBanai/HDF5-CSharp/files/7575947/hdf5_test.zip)

Hi @LiorBanai ， Maybe still need your help ,I follow your method to get the attribute, and still return null
Attach my code and h5 file

`            string filename = @"C:\Users\MLX\AppData\Local\HDF_Group\HDFView\app\samples\hdf5_test.h5";
            //get the attribute of file
            var fileid = Hdf5.OpenFile(filename);
            var df = Hdf5.ReadAttribute<String>(fileid, "");

            //get the attribute of /arrays/2D float array
            List<Hdf5Element> list = Hdf5.ReadTreeFileStructure(filename);
            var ds_2dfloat = list[2].GetChildren().ToList()[1];
            df = Hdf5.ReadAttribute<String>(ds_2dfloat.Id, null);`

**Comment by LiorBanai** [comment]
@marksimer  I'll check and update you.

Currently there isn't one method to get all the attributes of the file.

**Comment by Fokatu** [comment]
> @marksimer I'll check and update you.
> 
> Currently there isn't one method to get all the attributes of the file.

Hi，LiorBanai， is it possible to get all the attibutes of a file or a dataset now? Thanks!

**Comment by LiorBanai** [comment]
Hi @Fokatu ,I forgot about this.
I'll see what Ican do over the weekend and update you

**Comment by Fokatu** [comment]
> @Fokatu, when you ask "is it possible to get all the attributes of a file or a dataset now? " do you mean the name of the attributes or also the value itself (which can be of different type of course)

It is better to get the value at the same time.
Is it possible to obtain the data in the folliowing image? i.e., get the attribure name, type, size, and value at the same.
Thanks!
![image](https://user-images.githubusercontent.com/25919117/170797561-bd898c44-6b0e-4786-9c40-d6967643b9fa.png)

**Comment by LiorBanai** [comment]
Not sure how easy it is to read all data without the user specifying the data type but I'll check 🙂

**Comment by LiorBanai** [comment]
@Fokatu ,
a fix for reading all attributes should be ready in the coming days. FYI

**Comment by Fokatu** [comment]
> @Fokatu , a fix for reading all attributes should be ready in the coming days. FYI

Great!
