### ISSUE TITLE
ReadFlatFileStructure / ReadTreeFileStructure

### ISSUE THREAD

**Issue by Tomes14** [LiorBanai/HDF5-CSharp#167]
Hi,

I couldn't read the FileStructure but reading the Groups and Datasets work fine. On debugging your code.
It throw an exception on a group with many attributes. (An attempt was made to read or write to protected memory. Often times, this is an indication that other memory is damaged.) It's thrown on H5A.iterate! 

`            int Callback(long elementId, IntPtr intPtrName, ref H5L.info_t info, IntPtr intPtrUserData)
            {
                ulong idx2 = 0;
                long groupId = -1;
                long datasetId = -1;
                H5O.type_t objectType;
                var name = Marshal.PtrToStringAnsi(intPtrName);
                var userData = Marshal.PtrToStringAnsi(intPtrUserData);
                var fullName = CombinePath(userData, name);
                Hdf5ElementType elementType = Hdf5ElementType.Unknown;
                // this is necessary, since H5Oget_info_by_name is slow because it wants verbose object header data 
                // and H5G_loc_info is not directly accessible
                // only chance is to modify source code (H5Oget_info_by_name)
                groupId = (H5L.exists(elementId, name) >= 0) ? H5G.open(elementId, name) : -1L;
                if (H5I.is_valid(groupId) > 0)
                {

                    objectType = H5O.type_t.GROUP;
                    elementType = Hdf5ElementType.Group;
                    ulong attId = 0;
                    **_var index = H5A.iterate(groupId, H5.index_t.NAME, H5.iter_order_t.INC, ref attId, AttributeCallback,
                                Marshal.StringToHGlobalAnsi("/"));_**

                }...`
here is some Testdata which produces that error!
[TEST_2.zip](https://github.com/LiorBanai/HDF5-CSharp/files/7746980/TEST_2.zip)

**Comment by LiorBanai** [comment]
Thanks! I'll check this out🙂

**Comment by LiorBanai** [comment]
Hi, @Tomes14 ,
a fix for ReadStructure should be ready in the coming days. FYI

**Comment by Tomes14** [comment]
fine thank you!!!

**Comment by LiorBanai** [comment]
There were many changes/fixes in latest version
https://github.com/LiorBanai/HDF5-CSharp/releases/tag/V1.14.0

You can give it a try if report problems/issues.
Please create new issue if problem persist.
