### ISSUE TITLE
Read Attributes

### ISSUE THREAD

**Issue by Marco-Pellegrino** [LiorBanai/HDF5-CSharp#201]
Hi @LiorBanai !
thanks for working on such helpful tool!
I have successfully manage to read an .hdf5 file but I am currently facing an issue.

```csharp
public class Steps
{
    [Hdf5EntryName("STEP_0")] public double[,] STEP0 { get; set; }
    [Hdf5EntryName("STEP_1")] public double[,] STEP1 { get; set; }
} 


string fileName = "myFilePath.hdf5";

long fileId = -1;
try
{
    fileId = Hdf5.OpenFile(fileName, true);
    var disp = Hdf5.ReadObject<Steps>(fileId, "/MODEL_STAGE[1]/RESULTS/ON_NODES/DISPLACEMENTS/DATA");
}

```
The code works but I am currently thinking if there is a better way to solve the problem.
My issue is that the number of `STEP` are not pre defined and they can get really big. How would you suggest to solve the problem?

Creating 1000 times the following would give some downside `[Hdf5EntryName("STEP_X")] public double[,] STEP0 { get; set; }`?
I have attached a file in case you want to try

![image](https://user-images.githubusercontent.com/53620289/175981766-748a5192-06ca-42d6-b1f2-4cb3a534f69c.png)

https://strusoftgroup-my.sharepoint.com/:u:/g/personal/marco_pellegrino_strusoft_com/Ef0RbvDasD9PiwiwMUVeTb8BpCUTaSZafcuGgvwaDf7GXw?e=zbiHQv

**Comment by LiorBanai** [comment]
Hi @Marco-Pellegrino ,
Interesting use case. Give me few days to think about a generic/elegant  option to read such a file. Maybe ReadAllDatasetWithName(..)...

**Comment by Marco-Pellegrino** [comment]
thanks @LiorBanai !!!
it is already enough what you have showed me :)
don't worry in creating a better/elegant way

**Comment by LiorBanai** [comment]
Glad it helped you 🙂

**Comment by Marco-Pellegrino** [comment]
Hi @LiorBanai 
Do I need to do something particular to close the file?
Do I need also to close the group?

`Hdf5.close()` is enough?

**Comment by LiorBanai** [comment]
just call
Hdf5.CloseFile(fileId);

**Comment by Marco-Pellegrino** [comment]
Is there a way to see if the file has been closed?


I have tried to "manually" delete the file after calling the method but with no success because "the file is still open in your application"

**Comment by LiorBanai** [comment]
I'll check. if the file still in use after calling Hdf5.CloseFile(fileId); then it is a bug mostly likely

**Comment by Marco-Pellegrino** [comment]
The following approach `close` the file as expected.
I always make sure to close the file in case of exception with `try `and `catch`.
It seems to be a bug

```csharp
public class Steps
{
    [Hdf5EntryName("STEP_0")] public double[,] STEP0 { get; set; }
    [Hdf5EntryName("STEP_1")] public double[,] STEP1 { get; set; }
} 


string fileName = "myFilePath.hdf5";

long fileId = -1;
try
{
    fileId = Hdf5.OpenFile(fileName, true);
    var disp = Hdf5.ReadObject<Steps>(fileId, "/MODEL_STAGE[1]/RESULTS/ON_NODES/DISPLACEMENTS/DATA");
    hdf5.CloseFile(fileId);
}
catch
{
    hdf5.CloseFile(fileId);
}

```

**Comment by LiorBanai** [comment]
I'm able to reproduce it . Will update soon :)

**Comment by LiorBanai** [comment]
@Marco-Pellegrino Thanks for the Kofi donation!

**Comment by LiorBanai** [comment]
@Marco-Pellegrino  small question,
did you use my example above?
if so try adding the following coed before callnig close file:
```            
  Hdf5.CloseGroup(groupId);
```

full example:

```cs
        [TestMethod]
        public void TestLoops()
        {
            Hdf5.Settings.EnableH5InternalErrorReporting(true);
            Hdf5Utils.LogError = (s) => Errors.Add(s);
            string fileName = Path.Combine(folder, "files", "loop.H5");
            long fileId = -1;
            bool readOK = true;
            Dictionary<string, TabularData<double>> data = new Dictionary<string, TabularData<double>>();
            fileId = Hdf5.OpenFile(fileName, true);
            var groupId = Hdf5.CreateOrOpenGroup(fileId, "/MODEL_STAGE[1]/RESULTS/ON_NODES/DISPLACEMENT/DATA/");
            int step = 0;
            do
            {
                string name = $"STEP_{step++}";
                TabularData<double> disp = Hdf5.Read2DTable<double>(groupId, name);
                if (disp.Data != null)
                {
                    data.Add(name, disp);
                }
                else
                {
                    readOK = false;
                }
            } while (readOK);

            Hdf5.CloseGroup(groupId);
            Assert.IsTrue(data.Count==10);
            Hdf5.CloseFile(fileId);
            File.Delete(fileName);

        }
```

**Comment by Marco-Pellegrino** [comment]
thanks @LiorBanai !

I have went through my code and I have finally spotted the issue.
I was reading a different group before closing the previous.

I am working on this little app and reading the hdf5 file was required.
https://alpaca4d.github.io/

thanks a lot :)

**Comment by LiorBanai** [comment]
Great! and you gave me idea to close all opened handles when calling close so there won't be leaks if someone forget to close manually.

**Comment by LiorBanai** [comment]
> thanks @LiorBanai !
> 
> I have went through my code and I have finally spotted the issue.
> I was reading a different group before closing the previous.
> 
> I am working on this little app and reading the hdf5 file was required.
> https://alpaca4d.github.io/
> 
> thanks a lot :)

Why do you need to read h5 for that app? 🙂

**Comment by Marco-Pellegrino** [comment]
Glad that I have managed to give you some feedback!


> Why do you need to read h5 for that app? 🙂
> 
> Edit: wow that is impressive app you created. Bring me back to my mechanical engineering studies and FEA.

The FEA solver that I am currently using return an HDF5 file format which apparently is really fast to read and write.
The reason for the DotNet HDF5 is because I am building a tool for visual programming which required DotNet.

Your supervision made this possible as well
