### ISSUE TITLE
NuGet installation issue

### ISSUE THREAD

**Issue by cloud-rocket** [LiorBanai/HDF5-CSharp#235]
I am running into the following issue while installing the library on VS2022, .NET 4.8 project:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to resolve dependency 'HDF5.NET'. Source(s) used: 'nuget.org', 'Microsoft Visual Studio Offline Packages'.				
```

Any ideas?
Thanks

**Comment by LiorBanai** [comment]
Hi @cloud-rocket . this is very strange, I'm able to run restore of the nugets on my side and everything is running ok...
just for a test can you target different compilation?
