### ISSUE TITLE
WriteCompounds error

### ISSUE THREAD

**Issue by sharpwood** [LiorBanai/HDF5-CSharp#25]
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 852280:
  #000: C:\projects\hdf5\src\H5Tcompound.c line 350 in H5Tinsert(): not a datatype
    major: Invalid arguments to routine
    minor: Inappropriate type

**Comment by sharpwood** [comment]
https://github.com/reyntjesr/Hdf5DotnetTools/issues/6

**Comment by LiorBanai** [comment]
What is your configuration?. Net framework /. Net core x64/86?

**Comment by sharpwood** [comment]
.net core 3.1 x64

**Comment by LiorBanai** [comment]
Ok thanks.
I'll investigate.
beside the error are you able to work with the data or doe it broke the functionality?

**Comment by sharpwood** [comment]
I didn't find any problem with the function

**Comment by LiorBanai** [comment]
I'm fixing all those errors and will release new version later this week. Thanks for reporting this.
