### ISSUE TITLE
unable to resolve dependency PureHDF with version 1.16.3

### ISSUE THREAD

**Issue by Dream-Script** [LiorBanai/HDF5-CSharp#272]
Hi,

Using Nuget from Visual Studio, any idea what would cause this? 
If it try and get previous version 1.16.2 it gives same error but for HDF5.Net.

If i search on Nuget for PureHDF or HDF5.net, neither are found.

![image](https://user-images.githubusercontent.com/123725797/215041989-3e73c277-3a61-4e28-8eb7-575f64d21304.png)

Thanks

**Comment by LiorBanai** [comment]
HI @Dream-Script , It seems some issue on your  (access to nuget.org) I tried now on 2 different computers both versions is it was able to download the dependencies.

try to run "Dotnet restore"  from the CLI and see if it work. sometimes VS has issues fetching nugets.

**Comment by LiorBanai** [comment]
![image](https://user-images.githubusercontent.com/36262995/215048195-e89062f0-f199-48f6-bb1c-de8afb38d7a9.png)

**Comment by Dream-Script** [comment]
Hi @LiorBanai,
Would "Dotnet restore" only try and restore packages in my project that i have installed?
I can't get the HDF5-CSharp installed at all
do you know the command to try and install HDF5-CSharp through the CLI?

**Comment by LiorBanai** [comment]
Yeah , only for already added. I also create new project add added the nuget without issues.

What framework are you using? netframework? .net core?

you can try add it manually to the csproj and see if restore works 
```xml
  <ItemGroup>
    <PackageReference Include="HDF5-CSharp" Version="1.16.3" />
  </ItemGroup>
```

![nuget](https://user-images.githubusercontent.com/36262995/215057564-fef790f6-cf8f-4d31-bdc3-47985328a9d4.gif)

**Comment by Dream-Script** [comment]
netframework 4.7.2
aaa okay got it, if i create a class library and install HDF5-CSharp with Nuget it works, but if i try and install HDF5-CSharp into a webapplication project it fails.

**Comment by LiorBanai** [comment]
very strange. can you create new proejct and add it here for me to check? or write steps to reproduce it?

**Comment by LiorBanai** [comment]
@Apollo3zehn, Any idea?

**Comment by Dream-Script** [comment]
I created a basic c# webapplication project, same thing

i had to remove some file from the package "Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.1" so that it was less than 25mb

[testcSharpWebAppNuget.zip](https://github.com/LiorBanai/HDF5-CSharp/files/10519316/testcSharpWebAppNuget.zip)

**Comment by LiorBanai** [comment]
I can reproduce it. don't know what the issue but there is a workaround:
first add the PureHDF nuget dependency
![image](https://user-images.githubusercontent.com/36262995/215106583-c6a0219e-83e6-45a4-814e-3780d012db99.png)
and after that add the HDF5-Csharp and you will be able  to compile it

![image](https://user-images.githubusercontent.com/36262995/215106823-3ae6d735-532e-4db7-8666-f17f7b78ab72.png)

**Comment by Dream-Script** [comment]
lol, if i had clicked this option when i was trying earlier i would have installed PureHDF separately before installing HDF5-Csharp, just like you have suggested.
Thank you for the help!

![image](https://user-images.githubusercontent.com/123725797/215113653-3d1555b3-29f0-4383-ace9-ee58e0e3a761.png)

**Comment by LiorBanai** [comment]
@Apollo3zehn Actually I'm not so sure since in console application it works regardless of being prerelease. I suspect something with the web project template.

**Comment by Apollo3zehn** [comment]
Maybe the web application project uses the old .csproj style and/or the old Nuget packages.config file approach. AFAIK that the old system does not restore transient dependencies.

**Comment by LiorBanai** [comment]
you may be correct. The example project above is using the non sdk csproj format.
