### ISSUE TITLE
Unity3D: ReadTreeFileStructure and ReadFlatFileStructure return null

### ISSUE THREAD

**Issue by jamesbrownnz** [LiorBanai/HDF5-CSharp#274]
I'm manually including the dll's for hdf5  support in unity3d.
I can read and write datasets fine however, when I want to look at the ReadTreeFileStructure it returns null.
I think I must be missing a DLL or have an incorrect version.

The versions are as follows:
```
- Unity3D 2021.3.17f1
--
- hdf5.dll - 1.14.0

- HDF.PInvoke.1.10.dll - standard2.0 - 1.10.612
- HDF5CSharp.dll - standard2.0 - 1.16.3
- PureHDF.dll - standard2.0 - 1.0.0-alpha.23
- System.Memory.dll - standard2.0 - 4.5.5
- System.Resources.Extensions.dll - standard2.0 - 7.0.0
- System.Runtime.CompilerServices.Unsafe.dll - standard2.0 - 6.0.0
```

Unity3d is set to IL2CPP with the Api Compatibility Level set to  .NET framework 2.0

[error_example.zip](https://github.com/LiorBanai/HDF5-CSharp/files/10580750/error_example.zip)

**Comment by LiorBanai** [comment]
Hi @jamesbrownnz if you read the file outside of Unity does it works correctly? can you attach example hdf5 file?

**Comment by LiorBanai** [comment]
@jamesbrownnz checking. I see there is h5 file in the zip file

**Comment by jamesbrownnz** [comment]
Hi @LiorBanai yup, I've tested the file manually outside of unity3d.

**Comment by LiorBanai** [comment]
HI @jamesbrownnz I think I found the issue.
first. you can enable logging by using the EnableLogging methods:

![image](https://user-images.githubusercontent.com/36262995/216671470-00eaf58b-03a4-4f8d-bc77-d811b6ed909a.png)

Now I have seen you have different dll of hdf5.dll.
your has different size as the one from the compiled code
![image](https://user-images.githubusercontent.com/36262995/216671867-2535a77e-2c5a-408e-9148-64bd82ac9303.png)

and third, it seems the hdf5_hl.dll is indeed missing.
after adding those you can read it ok:
![image](https://user-images.githubusercontent.com/36262995/216671953-5cef5c47-03a0-4d98-86d6-74dd7e81a456.png).

attached working zip file
[unity.zip](https://github.com/LiorBanai/HDF5-CSharp/files/10581386/unity.zip)

**Comment by LiorBanai** [comment]
@jamesbrownnz I took it from the nuget dependency after building the HDF5-CSharp code

**Comment by jamesbrownnz** [comment]
Okay great, taking the nuget dependency from HDF5-CSharp made it work.
Do you know where it gets that dependency from?

**Comment by LiorBanai** [comment]
Not sure what to mean but the nuget has all the files inside it.
