### ISSUE TITLE
trying to update from nuget raise an error

### ISSUE THREAD

**Issue by Marco-Pellegrino** [LiorBanai/HDF5-CSharp#312]
Attempting to resolve dependencies for package 'HDF5-CSharp.1.17.0' with DependencyBehavior 'Lowest'
Unable to resolve dependency 'PureHDF'. Source(s) used: 'nuget.org'.

How can I solve the issue?
I am currently trying to "move" from windows app to macOs app and I am facing this issue

**Comment by LiorBanai** [comment]
Hi @Marco-Pellegrino,
This is probably due to the fact that PureHDF is still pre-release nuget. Please enable the pre release option so it can be used..

**Comment by Marco-Pellegrino** [comment]
thanks @LiorBanai !

It did worked
