### ISSUE TITLE
Get all the compounds names

### ISSUE THREAD

**Issue by sharpwood** [LiorBanai/HDF5-CSharp#37]
I write a lot of compounds to the HDF5 file, but I don't know how to get all the compounds names

**Comment by LiorBanai** [comment]
What kind of data do you need besides the elements names? I'm in the process of Adding ReadFileStructure(..) to the library.

**Comment by LiorBanai** [comment]
also can you supply me example file (unless there are some sensitive data inside) to work on it and verify the structure is correct?

**Comment by sharpwood** [comment]
My file is relatively simple. It's just composed of many components. I'm not familiar with HDF5, but use it as a compressed CSV container.

**Comment by LiorBanai** [comment]
Ok, I'll have it in a few days. a Structure-like/file will still be useful

**Comment by LiorBanai** [comment]
does this answer your needs?
```csharp

string fileName = @"FileStructure.h5";
var tree =Hdf5.ReadTreeFileStructure(fileName);
var flat = Hdf5.ReadFlatFileStructure(fileName);
```

![hdf5Structure](https://user-images.githubusercontent.com/36262995/79135753-82322400-7db8-11ea-91e2-b977190a5fd6.jpg)

**Comment by sharpwood** [comment]
I think it's good

**Comment by LiorBanai** [comment]
I have released new nuget package with those methods: https://www.nuget.org/packages/HDF5-CSharp/1.10.610.4

give it a try.
If you have same issues report back.

**Comment by LiorBanai** [comment]
there was a small bug in the method: the file stay opened after reading.
you can update you nuget version to 1.10.610.6
https://www.nuget.org/packages/HDF5-CSharp/1.10.610.6
