### ISSUE TITLE
Byte and SByte reversed

### ISSUE THREAD

**Issue by ChasenRanger** [LiorBanai/HDF5-CSharp#38]
https://github.com/LiorBanai/HDF5-CSharp/blob/2c4285e1cccd1ab2afc2b66c22d57ff81f920d20/HDF5-CSharp/Hdf5Common.cs#L112

Byte returns the type (signed) int8, signed byte returns the type uint8.

**Comment by LiorBanai** [comment]
you are correct. Thanks for noticing and reporting this

**Comment by LiorBanai** [comment]
you can update your nuget version to use 1.10.610.5:
https://www.nuget.org/packages/HDF5-CSharp/1.10.610.5
