### ISSUE TITLE
File opened but never closed

### ISSUE THREAD

**Issue by ChasenRanger** [LiorBanai/HDF5-CSharp#39]
https://github.com/LiorBanai/HDF5-CSharp/blob/8c2ec400f9ea647636135e135004191a73a63746/HDF5-CSharp/Hdf5Reader.cs#L217

If the file exists, it is opened in Read Only mode to generate tree/flat preview. Thereafter, it is left open in memory, and the managed ID (long fileid) is lost when the method exits.

**Comment by LiorBanai** [comment]
correct again :)

**Comment by LiorBanai** [comment]
https://www.nuget.org/packages/HDF5-CSharp/1.10.610.6
:)
