### ISSUE TITLE
WriteDatasetFromArray does nothing if dataset exists

### ISSUE THREAD

**Issue by ChasenRanger** [LiorBanai/HDF5-CSharp#41]
https://github.com/LiorBanai/HDF5-CSharp/blob/616adc9fe97c491c9a993f5e3724ad7ea7f2ebd4/HDF5-CSharp/Hdf5Dataset.cs#L196

The linked command attempts exclusively to _create_ the dataset. This means the below test fails to update int[] "blah":
```C#
long tef2 = Hdf5.CreateFile(Path.Combine(outPath, "blahtest2.h5"));
int[] blah = new int[5] { 1, 2, 4, 5, 0 };
Hdf5.WriteDatasetFromArray<int>(tef2, "blah", blah, null);
Hdf5.CloseFile(tef2);
var what = "???"; // breakpoint in VS to test h5 file contents independently before next write step
tef2 = Hdf5.OpenFile(Path.Combine(outPath, "blahtest2.h5"));
blah[4] = 6;
Hdf5.WriteDatasetFromArray<int>(tef2, "blah", blah, null); // This command throws several debug errors from PInvoke
Hdf5.CloseFile(tef2);
// loading the hdf5 file shows it only has {1, 2, 4, 5, 0} stored.
```
This does not strike me as intentional, as "WriteDatasetFromArray<>" is called by most higher order commands such as "WriteObject", and you'd expect to be able to update files opened with classes stored as Objects. I noticed that CreateGroup is explicit about opening instead of creating if the group already exists:
https://github.com/LiorBanai/HDF5-CSharp/blob/616adc9fe97c491c9a993f5e3724ad7ea7f2ebd4/HDF5-CSharp/Hdf5Groups.cs#L16
```C#
            return (GroupExists(groupId, groupName))
                ? H5G.open(groupId, Hdf5Utils.NormalizedName(groupName))
                : H5G.create(groupId, Hdf5Utils.NormalizedName(groupName));
```
So I tried this: 
```C#
long datasetId = testcase ? H5D.open(groupId, Hdf5Utils.NormalizedName(name)) : H5D.create(groupId, Hdf5Utils.NormalizedName(name), datatype, spaceId);
```
And by manually flagging open vs create, I could update the stored "blah" array with the first example.

bonus: here's the debug errors PInvoke throws:
```
HDF5-DIAG: Error detected in HDF5 (1.10.6) thread 37012:
  #000: C:\projects\hdf-pinvoke-1-10\CMake-hdf5-1.10.6\hdf5-1.10.6\src\H5D.c line 151 in H5Dcreate2(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #001: C:\projects\hdf-pinvoke-1-10\CMake-hdf5-1.10.6\hdf5-1.10.6\src\H5Dint.c line 337 in H5D__create_named(): unable to create and link to dataset
    major: Dataset
    minor: Unable to initialize object
  #002: C:\projects\hdf-pinvoke-1-10\CMake-hdf5-1.10.6\hdf5-1.10.6\src\H5L.c line 1592 in H5L_link_object(): unable to create new link to object
    major: Links
    minor: Unable to initialize object
  #003: C:\projects\hdf-pinvoke-1-10\CMake-hdf5-1.10.6\hdf5-1.10.6\src\H5L.c line 1833 in H5L__create_real(): can't insert link
    major: Links
    minor: Unable to insert object
  #004: C:\projects\hdf-pinvoke-1-10\CMake-hdf5-1.10.6\hdf5-1.10.6\src\H5Gtraverse.c line 851 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #005: C:\projects\hdf-pinvoke-1-10\CMake-hdf5-1.10.6\hdf5-1.10.6\src\H5Gtraverse.c line 627 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #006: C:\projects\hdf-pinvoke-1-10\CMake-hdf5-1.10.6\hdf5-1.10.6\src\H5L.c line 1628 in H5L__link_cb(): name already exists
    major: Links
    minor: Object already exists
HDF5-DIAG: Error detected in HDF5 (1.10.6) thread 37012:
  #000: C:\projects\hdf-pinvoke-1-10\CMake-hdf5-1.10.6\hdf5-1.10.6\src\H5Dio.c line 314 in H5Dwrite(): dset_id is not a dataset ID
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.6) thread 37012:
  #000: C:\projects\hdf-pinvoke-1-10\CMake-hdf5-1.10.6\hdf5-1.10.6\src\H5D.c line 337 in H5Dclose(): not a dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
```

**Comment by LiorBanai** [comment]
I tend to agree with you especially as your test stopped with exception during attempt to create again the dataset.

Logging debug message  that state that the dataset already exist before overriding it may also be usfeull

**Comment by ChasenRanger** [comment]
With my VS settings it actually does not stop with an exception, it just prints the HDF5-DIAG errors and continues along as if nothing has happened. That may or may not be relevant, but I felt I should clarify.

It also occurred to me, I only tested the case of replacing the array with an array of the same size. I'm not sure if replacing with an array of different sizes matters in HDF, but (or perhaps 'so') I can imagine a 'worst-case' where repeatedly changing sizes from 2000 to 1000 elements orphans 1000 elements-worth of memory in the file each time.

**Comment by LiorBanai** [comment]
Still, the end user may end up with inconsistent object/data in file and not know why.

it may be better to delete old datasets (if exist) before opening it for update and then recreate it. In this mode the memory should be reused for the data or free for other objects

**Comment by ChasenRanger** [comment]
Agreed, it took some time to track it down for me, and I wasn't trying to change its type.

A DeleteDataset and/or OverwriteDataset (or overwrite mode/flag for WriteDataset) would be very useful as well.

**Comment by LiorBanai** [comment]
yeah, OverrideExistingData is good option with a default of true since this is the most expected case when one updates object's data

**Comment by ChasenRanger** [comment]
So, something like this?

```C#
public static (int success, long CreatedgroupId) WriteDatasetFromArray<T>(long groupId, string name, Array dset, string datasetName = null, bool OverrideExistingData = true)
{
    int rank = dset.Rank;
    ulong[] dims = Enumerable.Range(0, rank).Select(i => { return (ulong)dset.GetLength(i); }).ToArray();
    ulong[] maxDims = null;
    var spaceId = H5S.create_simple(rank, dims, maxDims);
    var datatype = GetDatatype(typeof(T));
    var typeId = H5T.copy(datatype);
    if (datatype == H5T.C_S1)
    {
        H5T.set_size(datatype, new IntPtr(2));
    }
    long datasetId;
    var datasetExists = H5L.exists(groupId, Hdf5Utils.NormalizedName(name)) > 0;
    if (datasetExists)
    {
        datasetId = OverrideExistingData ? H5D.open(groupId, Hdf5Utils.NormalizedName(name)) : -1L;
    }
    else
    {
        datasetId = H5D.create(groupId, Hdf5Utils.NormalizedName(name), datatype, spaceId);
    }
    if (datasetId == -1L) return (-1L, -1L);

    GCHandle hnd = GCHandle.Alloc(dset, GCHandleType.Pinned);
    var result = H5D.write(datasetId, datatype, H5S.ALL, H5S.ALL, H5P.DEFAULT,
        hnd.AddrOfPinnedObject());
    hnd.Free();
    H5D.close(datasetId);
    H5S.close(spaceId);
    H5T.close(typeId);
    return (result, datasetId);
}
```
I had it return early if it fails, but that might be worth an exception. Not sure.

**Comment by LiorBanai** [comment]
yeah but it should be global setting for all data types (not only datasets).
The true/false should resides at Hdf5.Hdf5Settings class where all other settings are stored.

now that I think about it it also good to add ThrowOnError bool option there.

I plan to add those options this weekend probably.

**Comment by ChasenRanger** [comment]
Sounds good. Looking forward to it.

**Comment by LiorBanai** [comment]
https://www.nuget.org/packages/HDF5-CSharp/1.10.610.7
should works only also different size rewrites.
