### ISSUE TITLE
List silently fails when containing arrays

### ISSUE THREAD

**Issue by ChasenRanger** [LiorBanai/HDF5-CSharp#50]
When invoking FlushData() (as per example) on an object containing a list, the list is silently ignored.

If the basefile FlushData is made virtual, and the class implements an override FlushData() that forcibly tries to call WriteObject on the List, it throws a different error: "System.Reflection.TargetParameterCountException: Parameter count mismatch." 
Here is the call:
```csharp
Hdf5.WriteObject(GroupId, _ListOfArrays);
```
And here is the stack while inside the package:
> System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(object, System.Reflection.BindingFlags, System.Reflection.Binder, object[], System.Globalization.CultureInfo)
> System.Reflection.RuntimeMethodInfo.Invoke(object, System.Reflection.BindingFlags, System.Reflection.Binder, object[], System.Globalization.CultureInfo)
> System.Reflection.RuntimePropertyInfo.GetValue(object, object[])
> HDF5CSharp.Hdf5.WriteProperties(System.Type, object, long)
> HDF5CSharp.Hdf5.WriteObject(long, object, string)

**Comment by LiorBanai** [comment]
I have added support for basic collection (aka List<int> ..)>
In your example, what is _ListOfArrays?

**Comment by ChasenRanger** [comment]
In the example it would be List<int[]> or List<float[]>, but I encountered the silent discard even when my List was of custom class objects. I do not recall if I tried explicitly calling WriteObject on my List when it was custom class objects.

**Comment by ChasenRanger** [comment]
Figured I should edit to add, if I use a custom class (call it MyContainer) to store my array and make a list of those instead, List<MyContainer> still fails with the TargetParameterCountException above using the 610.8 version (fwiw all my previous notes were on 610.7, if that affects anything relevant).

**Comment by LiorBanai** [comment]
thanks. I am able to reproduce it.

**Comment by LiorBanai** [comment]
One option that I consider is for none primitive collections (e.g: list of custom type) a full dump of the object (aka byte[] of the object)  will be written. This will allow to write complex structure to the file but in this situation the h5 viewer will show "garbage" data. 

This will allow to write a object to h5 file but it will be readable only by reading it back via the library

**Comment by ChasenRanger** [comment]
I assume the larger problem comes in how to name/factor the elements into an H5 tree structure if they are themselves classes, not in writing the underlying data (given that any single custom class works fine)?

Assuming that is it, what about an interface or abstract class for custom classes to inherit that would allow for entries to be uniquely named, but otherwise function the same with WriteObject()? Say, a "string Name" property, which would behave like Hdf5EntryName(name) when used to write a collection?

In any case, the functionality of that option sounds useful as well, even if another workaround for custom classes is found, perhaps as an alternative (lazy, frankly) write mode.

**Comment by LiorBanai** [comment]
> I assume the larger problem comes in how to name/factor the elements into an H5 tree structure if they are themselves classes, not in writing the underlying data (given that any single custom class works fine)?
> 

yeah that is. since those are containers in them self, they are lacking the names o be represented in the h5 structure.
  
> Assuming that is it, what about an interface or abstract class for custom classes to inherit that would allow for entries to be uniquely named, but otherwise function the same with WriteObject()? Say, a "string Name" property, which would behave like Hdf5EntryName(name) when used to write a collection?
> 

That is one option. going forward I think we should have different formatters for writing. Typeless/contractless will try to write all fields/properties while different mode will write only those with h5 attributes.

Can you give small example  of such interface?

> In any case, the functionality of that option sounds useful as well, even if another workaround for custom classes is found, perhaps as an alternative (lazy, frankly) write mode.

**Comment by ChasenRanger** [comment]
So as it is right now, you can make a class like this:

```csharp
[Hdf5GroupName("Patient")]
class Patient
{
    // Fields
    [Hdf5EntryName("Firstname")]
    private string _firstname;
    [Hdf5EntryName("Lastname")]
    private string _lastname;
    
    public Patient()  { }

    public Patient(string first, string last)
    {
        _firstname = first;
        _lastname = last;
    }
}
```
If I saved this object at the top level it would look like this:
\
\Patient
\Patient\Firstname (= _firstname)
\Patient\Lastname (= _lastname)

If I wanted to have multiple patients saved at once, I believe I could use WriteObject() to name them uniquely one at a time using the optional groupName argument (otherwise, they use the [Hdf5GroupName()] specified at the class level), but they would still have to be separate objects to save/load independently. 

Looping back to lists/arrays, the write function for those calls the GetDataType(), which only accepts primitives at the moment. My suggestion, based partly on my limited understanding of inheritance and the functionality involved, is to also implement an interface/abstract class (whichever is more convenient) that includes a Name property that is also allowed/called for in this GetDataType() function. This will allow you to catch and use custom classes that base themselves on your helper interface/class, which then contains a name that is used for writing. Something like: 

```csharp
public interface ICustomClass
{
    public string Name;
}
public CustomClass : ICustomClass
{
    [Hdf5EntryName("Data")]
    public int[] data;
    [Hdf5EntryName("NotData")]
    public float ndata;

    public CustomClass() { }
    public CustomClass(string objName, IList<int> inData, float infloat)
    {
        Name = objName;
        data = inData.ToArray();
        ndata = infloat;
    }
}
```
Then in WriteDatasetFromArray (or its calling function), when it finds the type inherits from ICustomClass, it could create a group (ListSubGroup) based on the List/Array name, call WriteObject() on each of the ICustomClass inherited objects in turn, using the Name of each object as the groupname for WriteObject:
```csharp
long fileId = Hdf5.CreateFile(filename);
List<CustomClass> customList = new List<CustomClass>();
customList.Add(new CustomClass("One", dataArrayOne, floatOne); // some int[] dataArrayOne, float floatOne
customList.Add(new CustomClass("Two", dataArrayTwo, floatTwo); // some int[] dataArrayTwo, float floatTwo
Hdf5.WriteFromArray(fileId, "CustomList", customList.ToArray()); // converting to array is fine for example
```
This should lead to a structure like this:
\
\CustomList
\CustomList\One
\CustomList\One\Data // dataArrayOne
\CustomList\One\NotData // floatOne
\CustomList\Two
\CustomList\Two\Data // dataArrayTwo
\CustomList\Two\NotData // floatTwo
Which preserves the readability by other h5 readers. Reading it back might be a bit trickier, unless the Write operation also saves something like:
` \CustomList\Names // = string[] with {"One", "Two"}`
to keep track of which underlying groups to grab from, or the ReadArray for custom classes also requires an IList<string> to specify the expected names. Alternatively to both of those, the tree of the groupId to load List<CustomClass> from could be expanded and any groups with all the dataset names for the class as subgroups could be read in - in the above example, One and Two contain "Data" and "NotData", which means they can fit in as CustomClass.

**Comment by LiorBanai** [comment]
Now I get it. Nice idea! I'll give it a thought how to implement it. I may do it with a GetHdf5ObjectName (or something like that) which will allow to have custom logic for the name.. The base logic could be the name properly for example.
