### ISSUE TITLE
(Minor) Function throws generic "Exception"

### ISSUE THREAD

**Issue by ChasenRanger** [LiorBanai/HDF5-CSharp#53]
This one is not a bug, and I worry verges on nitpicking; however, similar issues have caused me problems in the past, so I feel inclined to mention it. I noticed that the referenced function (and the one below it) throw the primitive/generic Exception type, which is preferred against in MSDN guidelines ([e.g.](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/using-standard-exception-types)) due to being the generic / base exception. Something like InvalidOperationException or ArgumentException may be more applicable here.

https://github.com/LiorBanai/HDF5-CSharp/blob/8e51a6de64fa7d1bcc4948b89a5ce6e7fd2b425c/HDF5-CSharp/Hdf5Common.cs#L154

**Comment by LiorBanai** [comment]
or better yet ArgumentOutOfRangeException since we are trying to match a type to a specific range of valid options :)
