### ISSUE TITLE
Compound Dataset

### ISSUE THREAD

**Issue by Julian9620** [LiorBanai/HDF5-CSharp#82]
At first, your treeview structure from the hdf file is very nice and  i have been looking for something like this.
Next i want to deserialize a coumpound dataset. The description of this is in the property of the dataset. But i only find exsample code in which you have to know the data block. I don't know it but in the properties there is the description. Is it possible to get that dataset? 
I tried so far: deserialize to byte, to object and also i want to iterate about the "columns" but i don't get the "column count".
Exsample data from my side: int, string, float64[3]

**Comment by LiorBanai** [comment]
Hi,
the library was designed primary for known objects/structures.
I could try add dynamic reading of file.
Can you share a concrete h5 file for me to try and see how hard/work it to read it back to .net objects?

How would you like the output to look?

**Comment by Julian9620** [comment]
Wow, thank you for quick answer.
Unfortunately i cannot send you a h5-file beacause of github. I always show the hdf viewer and the image show you the exsample data. Until now i haven't any correct data so i create it synthetic. Maybe this can help to resolve it.

Also i saw you use reflection to get the properties from groups to know what is in there. Maybe it is possible to transfer to DataSets and after this cast every byte array to the given (primitive) type?

![image](https://user-images.githubusercontent.com/73472136/97882639-22837200-1d24-11eb-97a6-4d64745222de.png)

**Comment by LiorBanai** [comment]
can you add the same screenshot but with https://www.hdfgroup.org/downloads/hdfview/#download ?

This will show me more information of the underline data types of the dataset.

**Comment by LiorBanai** [comment]
BTW, you can also check this project https://github.com/Apollo3zehn/HDF5.NET
it may meet all your needs :)

**Comment by Julian9620** [comment]
So here is the new picture of data: Maybe this can help.

In the other project it seems that also know all types in the dataset before i can read it, right?

![image](https://user-images.githubusercontent.com/73472136/97885313-7ba0d500-1d27-11eb-9d87-abcda7883d9f.png)

**Comment by LiorBanai** [comment]
yeah this picture is better :)
I'll create same structure like file and see if I can parse it back without a backing structure.
I'll try this probably over the weekend and update you..

**Comment by Julian9620** [comment]
Thank you so much, i'm looking forward to your answer 😃

**Comment by LiorBanai** [comment]
@Julian9620, Can you send me to my mail (lior.banai@gmail.com) example file? you can edit any sensitive data with the HDF Viewer. 
I have problem creating compound data set with the library so an already created file will help.

**Comment by Julian9620** [comment]
Hi, i want to make sure that you get my mail 😄

**Comment by LiorBanai** [comment]
yeah got it 👍

**Comment by Julian9620** [comment]
Hi Lior, i have work with the known structs and it works very well so far. But there i saw that the HdfEntyName of the struct does not work in your tests. The "location1" still be the "location" like the struct field. How about SerializationBinder[https://docs.microsoft.com/de-de/dotnet/api/system.runtime.serialization.formatters.binary.binaryformatter.binder?view=netcore-3.1]?

**Comment by Julian9620** [comment]
And to the generic reading of compound datasets: What did you think about a dicttionary with the types? So it means you can go over the porperties of the dataset and save the string name in the key and the type of the row in the value. And back you get the dict and the binary dataset. After that there is a possibility to cast a row stream with the information from the dictionary?

**Comment by LiorBanai** [comment]
> still

That sound like a bug actually.. Can you point to a specific unit test for me to check this?

> And to the generic reading of compound datasets: What did you think about a dicttionary with the types? So it means you can go over the porperties of the dataset and save the string name in the key and the type of the row in the value. And back you get the dict and the binary dataset. After that there is a possibility to cast a row stream with the information from the dictionary?

Yeah, That is one  idea that I thought about. Was a little busy so have not got to it yet but I do plan to work on it very soon

**Comment by Julian9620** [comment]
> > Hi Lior, i have work with the known structs and it works very well so far. But there i saw that the HdfEntyName of the struct does not work in your tests. The "location1" still be the "location" like the struct field. How about SerializationBinder?
> > The edits are only for the link markdown
> 
> Glad to hear you managed to work with the current implementation :)
> regarding the naming, that sound like a bug actually.. Can you point to a specific unit test for me to check this?
That`s the UnitTest "WriteAndReadStructs" which takes the wdata2.
> 
> > And to the generic reading of compound datasets: What did you think about a dicttionary with the types? So it means you can go over the porperties of the dataset and save the string name in the key and the type of the row in the value. And back you get the dict and the binary dataset. After that there is a possibility to cast a row stream with the information from the dictionary?
> 
> Yeah, That is one idea that I thought about. Was a little busy so have not got to it yet but I do plan to work on it very soon
This will be very nice 😄

**Comment by RossSmyth** [comment]
Any update on this? I would be interested in this functionality.

**Comment by LiorBanai** [comment]
being busy later. Will try to get to is soon

**Comment by LiorBanai** [comment]
Will work on this in the coming weekend.

**Comment by LiorBanai** [comment]
Hi, is this still relevant?

**Comment by LiorBanai** [comment]
closing. please reopen if still needed
