### ISSUE TITLE
File Structure Reading Issue

### ISSUE THREAD

**Issue by kunekainen** [LiorBanai/HDF5-CSharp#89]
Hi. Both ReadTreeFileStructure() and ReadFlatFileStructure() methods return null value. Tested with many different files. What can I do?

**Comment by LiorBanai** [comment]
Hi,
I just tested it  in the existing unit test and it seems fine.
Can you send me example file to check? lior.banai@gmail.com

![image](https://user-images.githubusercontent.com/36262995/99185824-f836a900-2754-11eb-9e8f-62a960dcee1e.png)

**Comment by kunekainen** [comment]
Thank you very much. Yes I am mailling it right now.

**Comment by LiorBanai** [comment]
got it. I'll update you later today

**Comment by LiorBanai** [comment]
I run the TestReadStructure on your file and it does work:
![image](https://user-images.githubusercontent.com/36262995/99186214-96c40980-2757-11eb-8bf7-aadb75c9bbc6.png)


I expanded to test to log errors and print them to console. 
can you run the test on your side and check?

What is your environment ?
Which windows version? 
.net core/framework?
64/32 bit application?

**Comment by kunekainen** [comment]
Here it is. It is working with test file (Compiled your source code)

![hdfcstest](https://user-images.githubusercontent.com/41544172/99189795-1bbd1c00-2774-11eb-9a60-414819ea914d.png)

I am using Win10 Pro 64 Bit v2004
.NET 4.7.2
64 Bit App (Any CPU is selected)

I am not an experienced user BTW. I installed HDF5-CSharp via nuget and installed "hdf5-1.12.0-Std-win10_64-vs14" binaries. I did nothing more. Maybe I am doing something wrong.

**Comment by LiorBanai** [comment]
OK. I'll check a few things and will update you.

**Comment by LiorBanai** [comment]
try run your code without reference to hdf5-1.12.0-Std-win10_64-vs14. Maybe it is conflicting with my library that already reference 1.10.

**Comment by kunekainen** [comment]
I actually didn't add hdf5-1.12.0-Std-win10_64-vs14 to the references. When I installed your code from nuget it gave an error that hdf5.dll could not be found. So I just installed hdf5-1.12.0-Std-win10_64-vs14 the setup file. Here is my references:

![hdfcstest](https://user-images.githubusercontent.com/41544172/99191706-73ad5000-277f-11eb-9ac6-00e98ffc9932.png)

**Comment by kunekainen** [comment]
This is the error I get if I don't install the hdf5-1.12.0-Std-win10_64-vs14:

![err](https://user-images.githubusercontent.com/41544172/99192128-34343300-2782-11eb-903e-108552bd0d12.png)

**Comment by LiorBanai** [comment]
very strange.
try reference 
	<PackageReference Include="HDF.PInvoke.1.10" Version="1.10.610" />
and see if this works

**Comment by kunekainen** [comment]
Already tried that sir. Result is same.

Your source code and tests work flawlessly. But my solution does not.

If I add your project to my solution and uninstall the nuget package, does it work? What do you think?

**Comment by LiorBanai** [comment]
it may work but I'm not sure that is the correct approach.
Can you try create new minimal solution/project with the same issue and send me that project?

**Comment by kunekainen** [comment]
It didn't worked :)

Of course I'll do it.

**Comment by LiorBanai** [comment]
Ok, I can reproduce the issue with your solution.

I'll investigate later this week and update your.

**Comment by LiorBanai** [comment]
Ok I have found the issue. 
You are missing the runtimes native dll.
Nuget does not work with packages.config [See here](https://stackoverflow.com/questions/56154884/nuget-package-not-copying-native-dlls-on-build).

so first convert it to PackageReference: right click the file and select migrate:

![image](https://user-images.githubusercontent.com/36262995/99193545-69d91c00-2782-11eb-900d-1673dc12789e.png)


seconds , since those are native dll you need to specific you run time in the project itself (64 or 86):
![image](https://user-images.githubusercontent.com/36262995/99193573-8e34f880-2782-11eb-89e7-2d2dac6fa50b.png)

after that your projects run and read the file:
![image](https://user-images.githubusercontent.com/36262995/99193605-c4727800-2782-11eb-95b9-d56fb7497eaf.png)

**Comment by kunekainen** [comment]
Thank you very much for your time and effort. It finally worked.
