### ISSUE TITLE
NuGet failed to install on .NETFramework v4.6.1

### ISSUE THREAD

**Issue by chowchunkiu** [LiorBanai/HDF5-CSharp#94]
Hi,

I got the below error when trying to install the package, anything I can do to work around this?  Thank you.

`Could not install package 'HDF5-CSharp 1.11.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

**Comment by LiorBanai** [comment]
Hi @chowchunkiu ,
the library target .net standard which has partial support in .net framework 4.6.1.
Any reason for you to use 4.6.1?
I can try to add 4.6.1 to the nuget targets and see if it will work if you cannot upgrade to a newer version.

**Comment by chowchunkiu** [comment]
Hi @LiorBanai ,

Thanks for your quick response, we are using 4.6.1 due to legacy system reason.  So it would be nice if you can add support to .net framework 4.6.1 and I will try again.  Thank you.

**Comment by LiorBanai** [comment]
@chowchunkiu ,I'll add it over the weekend

**Comment by LiorBanai** [comment]
Hi @chowchunkiu .
I managed to reference the package in net461.

did you add it manually or via visual studio? if you are using visual studio it add other dependencies that are needed to reference netstand 2.0 in 461:
```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="HDF.PInvoke.1.10" version="1.10.610" targetFramework="net461" />
  <package id="HDF5-CSharp" version="1.11.1" targetFramework="net461" />
  <package id="System.Buffers" version="4.4.0" targetFramework="net461" />
  <package id="System.Memory" version="4.5.3" targetFramework="net461" />
  <package id="System.Numerics.Vectors" version="4.4.0" targetFramework="net461" />
  <package id="System.Resources.Extensions" version="4.6.0" targetFramework="net461" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.5.2" targetFramework="net461" />
</packages>
```
do you use packages.config file or packageReference?

for PackageReference you can use:
```xml
<ItemGroup>
    <PackageReference Include="HDF.PInvoke.1.10">
      <Version>1.10.610</Version>
    </PackageReference>
    <PackageReference Include="HDF5-CSharp">
      <Version>1.11.1</Version>
    </PackageReference>
    <PackageReference Include="System.Buffers">
      <Version>4.4.0</Version>
    </PackageReference>
    <PackageReference Include="System.Memory">
      <Version>4.5.3</Version>
    </PackageReference>
    <PackageReference Include="System.Numerics.Vectors">
      <Version>4.4.0</Version>
    </PackageReference>
    <PackageReference Include="System.Resources.Extensions">
      <Version>4.6.0</Version>
    </PackageReference>
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe">
      <Version>4.5.2</Version>
    </PackageReference>
  </ItemGroup>
```

**Comment by chowchunkiu** [comment]
Finally able to install the library via NuGet!  Great thanks @LiorBanai!

**Comment by LiorBanai** [comment]
Glad I could help @chowchunkiu

**Comment by LiorBanai** [comment]
I'll close this. If you have other questions /problems please feel free to open new issue
